server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mariemMoula/Config_Repo_User_Product_Microservice_AXON.git
          clone-on-start: true
          search-paths: '{application}' #This is the path to the configuration files in the git repository which means that the configuration files are stored in the root of the repository.
          try-master-branch: false